name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and test Docker image
      run: |
        docker build -t ecommerce-app .
        docker run ecommerce-app

    - name: Check pytest test discovery
      run: |
        pytest --collect-only  

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
      env:
        PYTHONPATH: ./app  